### PR TITLE
Pull Request for Code Review

### PR DESCRIPTION
**Pull request by fredericomba**
This is a pull request opened for receiving a code review.

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi team👋,
You have done a good job💪  with this project so far.
Here are a few changes we have to make to get this project approved🙂
* [x] Navigation bar
Let us take a critical look at the original [page](https://thenextweb.com/) and look at the way the navbar and its component behave a the different breakpoints🙂. Below is a snippet of these behaviors
- At LG
Screenshot from 2019-10-31 17-25-15
The Tnw logo is not visible at this breakpoint

- At MD
Screenshot from 2019-10-31 16-50-42
Take a careful look at the behavior of the Tnw logo and the black navbar and replicate the same.

- At SM
Screenshot from 2019-10-31 16-53-23
#### Let us use font awesome for the Hamburger and search icon in the navbar

- [x] Footer
The element in the footer does not change and the element beneath the social media icons display inline
#### This is for the original
Screenshot from 2019-10-31 17-03-45
#### This is the clone
Screenshot from 2019-10-31 17-05-19

* [x] let fix the warnings returned by the[ validator ](https://validator.w3.org) after uploading the index file.🙂 

### That is it, Guys, Kindly do these changes and submit the project for review🙂 

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. i would be happy to assist you.
#### Happy coding🙂 🙂

**Comment by Anna-Myzukina** [comment]
### Hi Team!  
#### Wow, your project looks :+1: 
##### Please check responsive of your project
Screenshot from 2019-11-01 01-00-27




Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  🛑

### Hello team  🌟

**Good work implementing the changes, but we need to fix the issues below before moving on ⬇️** 

1. The text in the 3 top articles isn't responsive on small screens please fix that, also add an overlay on top of the article's images, try to make it look like the original page.

2. On small and medium screen sizes the TNW logo should disappear from the top article and be only in the navbar.

### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

**Comment by mikenath223** [comment]
Effected corrections as advised.
Thanks

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @frederico-miranda  and @mikenath223 :wave: 

You guys are really doing great. I love your perseverance and drive. Please let's address the second issue in @Redvanisation's review.

**Theirs**
review-tnw-original


**Yours**
review-tnw-clone


**Consider setting the `display` property of that element to `none` at the medium and small breakpoints**

**Kindly submit another code review request after fixing that issue**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by fredericomba** [comment]
@ebukaume @Anna-Myzukina 

I've implemented changes for addressing the issues you've raised. You can see from the screenshots below from a live version of the latest page that the behavior of the logo now is the expected one.

https://github.com/mikenath223/Building-with-Responsive-Design/blob/feature-branch/images/screenshots/006.png
https://github.com/mikenath223/Building-with-Responsive-Design/blob/feature-branch/images/screenshots/007.png
https://github.com/mikenath223/Building-with-Responsive-Design/blob/feature-branch/images/screenshots/008.png

I've also added a new link to the live version of the page so that you may not mistakenly see a stale version of the page instead of the latest one (The service provided by _raw.githack.com_ does not automatically flushes the cache). This is the link for the latest live version of the page:

https://rawcdn.githack.com/mikenath223/Building-with-Responsive-Design/cbde042a2878d3da04799f59786496f6e619a2b0/index.html

@Redvanisation - About the issue nº 1 you've raised: I'm not sure what the issue is about, but my coding partner has informed that that issue has already been fixed. I've looked at the page and it does have a behavior similar to the original page.

If there are remaining issues please do let me know.

**Comment by shloch** [comment]
### Great Job Frederico Miranda  & Michgolden Uzodimma 
 we've finally finished guys 👍👍👍

**This project is considered valid 👏👏👏** 

You can merge this request

**Comment by mikenath223** [comment]
Thanks for that we love the support and adjustments given.
We will now merge to master. : )

**Pull request merged**
